### PR TITLE
Add PersistentVolume

### PR DESCRIPTION
**Pull request by paralin**
Introduces PersistentVolume and PersistentVolumeClaim

Towards #13

### CODE REVIEW

**Comment by brosner** [comment]
Excellent! Thank you for the PR. Can you fix the flake8 issues being reported on Travis CI? I suspect the tests are failing, but we can at least get past the flake8 issues.

**Comment by paralin** [comment]
@brosner I think it's just a spacing issue. I'll fix it soon here.

**Comment by brosner** [comment]
I've merged this because I am about to do a release and don't want the whitespace to hold it up. I'll correct it on master. Thank you for the contribution!

**Comment by pcm32** [comment]
I did correct the whiteline, the build was passing after I submitted the change, once you asked for it.

**Pull request merged**
